# Helmet API Definition

[Main]
    id = "spacewalk_helmet"
    name = "SpaceWalk - Helmet"
    description = "A Lightweight Cloud Native API Gateway"
    timeout = "30s"
    service_url = "{$serviceURL:http://127.0.0.1:8000}"
    # These headers will be applied to all endpoints http calls
    headers = [ ["Content-Type", "application/json"] ]

[Security]
    # Supported Types are basic, bearer and api_key and none
    scheme = "api_key"

    [Security.Basic]
        username = "{$authUsername:default}"
        password = "{$authPassword:default}"
        header = ["Authorization", "Basic base64(username:password)"]

    [Security.ApiKey]
        header = ["X-API-KEY", "{$authApiKey:6c68b836-6f8e-465e-b59f-89c1db53afca}"]

[[Endpoint]]
    id = "GetSystemHealth"
    name = "Get system health"
    description = ""
    method = "get"
    public = true
    headers = []
    parameters = []
    uri = "/_health"
    body = ""

[[Endpoint]]
    id = "GetSystemReadiness"
    name = "Get system readiness"
    description = ""
    method = "get"
    public = true
    headers = []
    parameters = []
    uri = "/_ready"
    body = ""

[[Endpoint]]
    id = "GetEndpoints"
    name = "Get Endpoints"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/endpoint"
    body = ""

[[Endpoint]]
    id = "GetAuthMethods"
    name = "Get Auth Methods"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/method"
    body = ""

[[Endpoint]]
    id = "GetAuthMethod"
    name = "Get Auth Method"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/method/{$id}"
    body = ""

[[Endpoint]]
    id = "CreateAuthMethod"
    name = "Create Auth Method"
    description = ""
    method = "post"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/method"
    body = """
    {
        "name": "{$name:customers_public}",
        "type": "{$type:key_authentication}",
        "description": "{$description}",
        "endpoints": "{$endpoints:order_service}"
    }
    """

[[Endpoint]]
    id = "UpdateAuthMethod"
    name = "Update Auth Method"
    description = ""
    method = "put"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/method/{$id}"
    body = """
    {
        "name": "{$name:customers_public}",
        "type": "{$type:key_authentication}",
        "description": "{$description}",
        "endpoints": "{$endpoints:order_service}"
    }
    """

[[Endpoint]]
    id = "DeleteAuthMethod"
    name = "Delete Auth Method"
    description = ""
    method = "delete"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/method/{$id}"
    body = ""

[[Endpoint]]
    id = "GetBasicAuthKeys"
    name = "Get Basic Auth Keys"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/basic"
    body = ""

[[Endpoint]]
    id = "GetBasicAuthKey"
    name = "Get Basic Auth Key"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/basic/{$id}"
    body = ""

[[Endpoint]]
    id = "CreateBasicAuthKey"
    name = "Create Basic Auth Key"
    description = ""
    method = "post"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/basic"
    body = """
    {
        "name": "{$name:basic}",
        "username": "{$username:admin}",
        "password": "{$password:admin}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "UpdateBasicAuthKey"
    name = "Update Basic Auth Key"
    description = ""
    method = "put"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/basic/{$id}"
    body = """
    {
        "name": "{$name:basic}",
        "username": "{$username:admin}",
        "password": "{$password:admin}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "DeleteBasicAuthKey"
    name = "Delete Basic Auth Key"
    description = ""
    method = "delete"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/basic/{$id}"
    body = ""

[[Endpoint]]
    id = "GetAuthApiKeys"
    name = "Get Auth API Keys"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/key"
    body = ""

[[Endpoint]]
    id = "GetAuthApiKey"
    name = "Get Auth API Key"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/key/{$id}"
    body = ""

[[Endpoint]]
    id = "CreateAuthApiKey"
    name = "Create Auth API Key"
    description = ""
    method = "post"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/key"
    body = """
    {
        "name": "{$name:api}",
        "apiKey": "{$apiKey:x-x-x-x}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "UpdateAuthApiKey"
    name = "Update Auth API Key"
    description = ""
    method = "put"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/key/{$id}"
    body = """
    {
        "name": "{$name:api}",
        "apiKey": "{$apiKey:x-x-x-x}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "DeleteAuthApiKey"
    name = "Delete Auth API Key"
    description = ""
    method = "delete"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/key/{$id}"
    body = ""

[[Endpoint]]
    id = "GetAuthOauthKeys"
    name = "Get Auth Oauth Keys"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/oauth"
    body = ""

[[Endpoint]]
    id = "GetAuthOauthKey"
    name = "Get Auth Oauth Key"
    description = ""
    method = "get"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/oauth/{$id}"
    body = ""

[[Endpoint]]
    id = "CreateAuthOauthKey"
    name = "Create Auth Oauth Key"
    description = ""
    method = "post"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/oauth"
    body = """
    {
        "name": "{$name:oauth}",
        "clientID": "{$clientID:x-x-x-x}",
        "clientSecret": "{$clientSecret:y-y-y-y}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "UpdateAuthOauthKey"
    name = "Update Auth Oauth Key"
    description = ""
    method = "put"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/oauth/{$id}"
    body = """
    {
        "name": "{$name:oauth}",
        "clientID": "{$clientID:x-x-x-x}",
        "clientSecret": "{$clientSecret:y-y-y-y}",
        "meta": "{$meta:x=1;y=2}",
        "authMethodID": {$authMethodID:1}
    }
    """

[[Endpoint]]
    id = "DeleteAuthOauthKey"
    name = "Delete Auth Oauth Key"
    description = ""
    method = "delete"
    public = false
    headers = []
    parameters = []
    uri = "/_api/v1/auth/oauth/{$id}"
    body = ""