# App configs
app:
    # App name
    name: ${WALNUT_APP_NAME:-walnut}
    # Env mode (dev or prod)
    mode: ${WALNUT_APP_MODE:-prod}
    # HTTP port
    port: ${WALNUT_API_PORT:-80}
    # Hostname
    hostname: ${WALNUT_API_HOSTNAME:-127.0.0.1}
    # TLS configs
    tls:
        status: ${WALNUT_API_TLS_STATUS:-off}
        crt_path: ${WALNUT_API_TLS_PEMPATH:-cert/server.crt}
        key_path: ${WALNUT_API_TLS_KEYPATH:-cert/server.key}

    # API Configs
    api:
        key: ${WALNUT_API_KEY:-6c68b836-6f8e-465e-b59f-89c1db53afca}

    # Runtime, Requests/Response and Walnut Metrics
    metrics:
        prometheus:
            # Route for the metrics endpoint
            endpoint: ${WALNUT_METRICS_PROM_ENDPOINT:-/_metrics}

    # Application Database
    database:
        # Database driver (sqlite3, mysql)
        driver: ${BEETLE_DATABASE_DRIVER:-sqlite3}
        # Database Host
        host: ${BEETLE_DATABASE_MYSQL_HOST:-localhost}
        # Database Port
        port: ${BEETLE_DATABASE_MYSQL_PORT:-3306}
        # Database Name
        name: ${BEETLE_DATABASE_MYSQL_DATABASE:-walnut.db}
        # Database Username
        username: ${BEETLE_DATABASE_MYSQL_USERNAME:-root}
        # Database Password
        password: ${BEETLE_DATABASE_MYSQL_PASSWORD:-root}

    # Log configs
    log:
        # Log level, it can be debug, info, warn, error, panic, fatal
        level: ${WALNUT_LOG_LEVEL:-info}
        # Output can be stdout or abs path to log file /var/logs/walnut.log
        output: ${WALNUT_LOG_OUTPUT:-stdout}
        # Format can be json
        format: ${WALNUT_LOG_FORMAT:-json}
