# App configs
app:
    # App name
    name: ${DRIFTER_APP_NAME:-helmet}
    # Env mode (dev or prod)
    mode: ${DRIFTER_APP_MODE:-dev}
    # HTTP port
    port: ${DRIFTER_API_PORT:-8000}
    # Hostname
    hostname: ${DRIFTER_API_HOSTNAME:-127.0.0.1}
    # TLS configs
    tls:
        status: ${DRIFTER_API_TLS_STATUS:-off}
        crt_path: ${DRIFTER_API_TLS_PEMPATH:-cert/server.crt}
        key_path: ${DRIFTER_API_TLS_KEYPATH:-cert/server.key}

    # Global timeout
    timeout: ${DRIFTER_API_TIMEOUT:-50}

    # API Configs
    api:
        key: ${DRIFTER_API_KEY:-6c68b836-6f8e-465e-b59f-89c1db53afca}

    # Runtime, Requests/Response and Helmet Metrics
    metrics:
        prometheus:
            # Route for the metrics endpoint
            endpoint: ${DRIFTER_METRICS_PROM_ENDPOINT:-/_metrics}

    # Application Database
    database:
        # Database driver (sqlite3, mysql)
        driver: ${DRIFTER_DATABASE_DRIVER:-sqlite3}
        # Database Host
        host: ${DRIFTER_DATABASE_MYSQL_HOST:-localhost}
        # Database Port
        port: ${DRIFTER_DATABASE_MYSQL_PORT:-3306}
        # Database Name
        name: ${DRIFTER_DATABASE_MYSQL_DATABASE:-helmet.db}
        # Database Username
        username: ${DRIFTER_DATABASE_MYSQL_USERNAME:-root}
        # Database Password
        password: ${DRIFTER_DATABASE_MYSQL_PASSWORD:-root}

    # Endpoint Configs
    endpoint:
        # Orders Internal Service
        - name: order_service
          active: true
          proxy:
            listen_path: "/orders/v2/*"
            upstreams:
                balancing: roundrobin
                targets:
                    - target: https://httpbin.org/anything/orderService1/v2
                    - target: https://httpbin.org/anything/orderService2/v2
                    - target: https://httpbin.org/anything/orderService3/v2
                    - target: https://httpbin.org/anything/orderService4/v2
            http_methods:
                - ANY
            authentication:
                status: on
                auth_methods:
                    - 1
            rate_limit:
                status: off
            circuit_breaker:
                status: off

        # Customers Internal Service
        - name: customer_service
          active: true
          proxy:
            listen_path: "/customer/v2/*"
            upstreams:
                balancing: random
                targets:
                    - target: https://httpbin.org/anything/customerService1/v2
                    - target: https://httpbin.org/anything/customerService2/v2
                    - target: https://httpbin.org/anything/customerService3/v2
                    - target: https://httpbin.org/anything/customerService4/v2
            http_methods:
                - GET
                - POST
                - PUT
                - DELETE
            authentication:
                status: on
                auth_methods:
                    - 1
            rate_limit:
                status: off
            circuit_breaker:
                status: off

    # Log configs
    log:
        # Log level, it can be debug, info, warn, error, panic, fatal
        level: ${DRIFTER_LOG_LEVEL:-info}
        # Output can be stdout or abs path to log file /var/logs/helmet.log
        output: ${DRIFTER_LOG_OUTPUT:-stdout}
        # Format can be json
        format: ${DRIFTER_LOG_FORMAT:-json}
